package com.mystudy.ex01_exception;

public class ExceptionFinally {
	 
	public static void main(String[] args) {
		// try ~ catch ~ finally
		System.out.println("---- main() 시작 -----");
		int num = 20;
		int result = 0;
		try {
			System.out.println(">> try문 시작 ");
			num = 30;
			result = 100 / num;
		    System.out.println(">> 연산처리 정상 종료 ");
			System.out.println(">> try문 종료 ");
		} catch(ArithmeticException e) {
			System.out.println(">>>> catch 문 실행 ");
		} finally {
			System.out.println("***> finally : 항상실행 (무조건)");
		}
	    System.out.println("---------------------------");
	    
		
		
		
		System.out.println("----- main() 종료 -----");
		
	}
	

}
